import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "MH-YT",
  description: "Generated by create next app",
  
};
const myFont = localFont({
  src: "./assets/Fontspring-DEMO-proximanovaexcn-regular.otf",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
